### ISSUE TITLE
Interfacing with methods inherited from parent virtual classes (like interfaces).

### ISSUE THREAD

**Issue by AV00** [scapix-com/scapix#32]
I was trying to use methods in an interface object that was defined in a parent class but there's no bridging code being created.

A quick example:
```
class test_inheritance
{
public:
  int
  method1 (void)
  {
    return 3;
  }
};

class test_inheritance2 : public test_inheritance, public scapix::bridge::object<test_inheritance2>
{
public:
  test_inheritance2 () {}

  int
  method2 (void)
  {
    return method1 ();
  }
};
```
I would like to call method1() directly from the bridged languages instead of having to go through method2(). Is that possible ?

**Comment by Boris-Rasin** [comment]
Both interfaces will be bridged if you do it this way:

```c++
class test_inheritance : public scapix::bridge::object<test_inheritance>
{
public:
  int
  method1 (void)
  {
    return 3;
  }
};

class test_inheritance2 : public test_inheritance
{
public:
  test_inheritance2 () {}

  int
  method2 (void)
  {
    return method1 ();
  }
};
```

**Comment by E-AV0** [comment]
CONFIDENTIAL

Thanks, that indeed does work.


[cid:29cc8228-2e13-4902-bee5-2562fa6eb2f2]

Andrea Vallinotto

Mobile Developer Lead

Ermes – Intelligent Web Protection

www.ermes.company<https://www.ermes.company/>








________________________________
Da: Boris Rasin ***@***.***>
Inviato: martedì 21 dicembre 2021 15:47
A: scapix-com/scapix ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: Re: [scapix-com/scapix] Interfacing with methods inherited from parent virtual classes (like interfaces). (Issue #32)


Both interfaces will be bridged if you do it this way:

class test_inheritance : public scapix::bridge::object<test_inheritance>
{
public:
  int
  method1 (void)
  {
    return 3;
  }
};

class test_inheritance2 : public test_inheritance
{
public:
  test_inheritance2 () {}

  int
  method2 (void)
  {
    return method1 ();
  }
};

—
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fscapix-com%2Fscapix%2Fissues%2F32%23issuecomment-998837879&data=04%7C01%7Ca.vallinotto%40ermes.company%7C7eede55cfed54c80a5a708d9c490c166%7C889acf573353418fb4ebdc346e26f311%7C0%7C0%7C637756948264690776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=A0DxGWuNphTr%2FIt%2BjsThDnYLtQpk6ijkq1iHiQfF8wM%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATWQIYKAJKFNUNOPW6C3WE3USCHOPANCNFSM5KQJADAA&data=04%7C01%7Ca.vallinotto%40ermes.company%7C7eede55cfed54c80a5a708d9c490c166%7C889acf573353418fb4ebdc346e26f311%7C0%7C0%7C637756948264690776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1q%2BPBBIK%2FqiFcsIoZW7Hj9%2FE3NV7xvZHxz7HCQLafJE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ca.vallinotto%40ermes.company%7C7eede55cfed54c80a5a708d9c490c166%7C889acf573353418fb4ebdc346e26f311%7C0%7C0%7C637756948264690776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S%2BYH5PP7UwaoLpPveYZ70flUNg6%2B4mcAxYnEII4tKW4%3D&reserved=0> or Android<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ca.vallinotto%40ermes.company%7C7eede55cfed54c80a5a708d9c490c166%7C889acf573353418fb4ebdc346e26f311%7C0%7C0%7C637756948264690776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v8rLeK3giTXRxt%2FZBkdkTDFbUqA14l7fG6dqyPHT4rc%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


CONFIDENTIAL
