### ISSUE TITLE
What is this license?

### ISSUE THREAD

**Issue by JonasVautherin** [scapix-com/scapix#9]
How does this license compare to well-known open source licenses like Apache2, MIT, BSD etc? Why is there a need for a custom one?

**Comment by Boris-Rasin** [comment]
Just like the licenses you mention, Scapix license allows using Scapix free of charge for any kind of project, commercial or open source. Unlike the licenses you mention, Scapix license does not allow modification and/or redistribution of Scapix project itself.

The idea was to leave the possibility for a commercial version at some point in the future, in addition to the free version available now.

**Comment by JonasVautherin** [comment]
I see. Thanks.

**Comment by ethindp** [comment]
> Just like the licenses you mention, Scapix license allows using Scapix free of charge for any kind of project, commercial or open source. Unlike the licenses you mention, Scapix license does not allow modification and/or redistribution of Scapix project itself.

I'm really late to the party, but you may wish to clarify this, a lot, in the license. As it currently stands, the licenses text does not indicate this, at all. By the text of the license (which is how it would be applied under courts within jurisdictions of the United States) I would be prohibited from incorporating Scapix into any open-source projects because I may need to include headers from it, or I may wish to use it as a part of my build system so my repo doesn't consist of 30 percent auto-generated code or something.

A much better idea would be to adopt how OSS projects work: license everything under open source by default, but if people want support or similar, require them to buy a license. At least then things wouldn't look so awkward and it would be a lot more obvious what the boundaries are.
